"""The doctrine check 46 compares against: this plugin's reference names and code terms, frozen.

GENERATED on 2026-09-30 from skills/config-auditor/references/ - do not edit by hand.
Frozen rather than read at run time: a reference page added to the plugin changed findings in
consuming projects while the auditor's sha stayed the same. Regenerating it is a deliberate change
of the auditor, and moves its sha.
"""

DOCTRINE_REFERENCE_NAMES = frozenset({
    'agent-anatomy.md',
    'agents-md-anatomy.md',
    'antipatterns.md',
    'audit-checklist.md',
    'claude-md-anatomy.md',
    'copilot-anatomy.md',
    'cursor-anatomy.md',
    'gemini-anatomy.md',
    'hooks-anatomy.md',
    'mcp-anatomy.md',
    'official-links.md',
    'plugin-anatomy.md',
    'rules-anatomy.md',
    'runtime-data.md',
    'settings-permissions-anatomy.md',
    'skill-anatomy.md',
    'skill-runtime-mechanisms.md',
})

# 1199 code terms (text between backticks, 2 to 60 characters).
DOCTRINE_CODE_TERMS = frozenset({
    ' !',
    ' (',
    ' (claude.ai upload and ',
    ' *',
    ' and ',
    ' and ends with ',
    ' before the subcommand in an allow rule (',
    ' exempt) | no warning documented [inference: silent] → **',
    ' exposes ',
    ' file-suggestion command (',
    ' in ',
    ' injection cannot fail the whole invocation (',
    ' is ',
    ' menu and every ',
    ' menu, typed ',
    ' never crosses a dot. Bare ',
    ' nothing is shown. The hook never fires. Casing counts: ',
    ' opens a bracket expression. Only a ',
    ' or ',
    ' server of ',
    ' that **cannot** form one — ',
    ' | exact string, or exact list split on ',
    '!~/…',
    '""',
    '"*"',
    '"**/shop-monorepo/CLAUDE.md"',
    '"."',
    '"B*"',
    '"Bash(git *)"',
    '"Edit(*.ts)"',
    '"GEMINI.md"',
    '"Helps with UI components."',
    '"Task"',
    '"\\"${CLAUDE_PLUGIN_ROOT}\\"/scripts/check.sh"',
    '"agents": ["./agents/", "./extra-agents/"]',
    '"allow"',
    '"auto"',
    '"autoMemoryEnabled": false',
    '"command": "node", "args": ["${CLAUDE_PLUGIN_ROOT}/…"]',
    '"doctor": "off"',
    '"mcp__*"',
    '"name-only"',
    '"node scripts/lint.js"',
    '"off"',
    '"on"',
    '"user-invocable-only"',
    '"worktree"',
    '## Agents directory',
    '## SSR',
    '$( … )',
    '$()',
    '$ARGUMENTS',
    '$ARGUMENTS[N]',
    '$CLAUDE_PLUGIN_OPTION_<KEY>',
    '$CLAUDE_PLUGIN_ROOT/scripts/x.sh',
    '$N',
    '$SHOP_MCP_TOKEN',
    '$VAR',
    '$name',
    '${',
    '${CLAUDE_EFFORT}',
    '${CLAUDE_PLUGIN_DATA}',
    '${CLAUDE_PLUGIN_ROOT}',
    '${CLAUDE_PROJECT_DIR:-.}',
    '${CLAUDE_PROJECT_DIR}',
    '${CLAUDE_SESSION_ID}',
    '${CLAUDE_SKILL_DIR}',
    '${SHOP_MCP_TOKEN}',
    '${VAR:-default}',
    '${VAR}',
    '${user_config.*}',
    '${user_config.KEY}',
    '${…}',
    '&&',
    "': '",
    '( … )',
    ') being converted to a colon (',
    '), and is off when ',
    '). ',
    '): a critical-path removal (',
    '); in ',
    '**',
    '** (deny and ask only) carves paths out of the ',
    '**/',
    '**/*.{css,scss}',
    '**/.claude/settings.local.json',
    '**/src/**',
    '*.bak',
    '*.disabled',
    '*.instructions.md',
    '*.shop.example',
    '*AUTH*',
    '*KEY*',
    '*Mcpjson*',
    '*PASSWORD*',
    '*SECRET*',
    '*TOKEN*',
    '*_SECRET',
    '*_TOKEN',
    '+x',
    ', ',
    ', an unguarded ',
    ', spaces, ',
    '---',
    '--add-dir',
    '--agent',
    '--agents',
    '--append-system-prompt',
    '--bare',
    '--debug',
    '--disallowedTools',
    '--fix',
    '--help',
    '--json',
    '--mcp-config',
    '--model',
    '--permission-mode',
    '--plugin-dir',
    '--runtime',
    '--runtime <InstructionsLoaded log>',
    '--safe-mode',
    '--setting-sources',
    '--settings',
    '--settings \'{"disableAllHooks": true}\'',
    '--strict',
    '--strict-mcp-config',
    '--transport http',
    '-p',
    '. The ',
    '.*',
    '..',
    '../',
    '../shared',
    './',
    './.claude/CLAUDE.md',
    './CLAUDE.md',
    './path',
    '.agent.md',
    '.agents/',
    '.agents/skills/',
    '.agents/skills/<name>/SKILL.md',
    '.chatmode.md',
    '.claude',
    '.claude-plugin/',
    '.claude-plugin/plugin.json',
    '.claude/',
    '.claude/AGENTS.md',
    '.claude/CLAUDE.md',
    '.claude/agents',
    '.claude/agents/',
    '.claude/agents/<verifier>.md',
    '.claude/audit.local.json',
    '.claude/commands',
    '.claude/commands/',
    '.claude/commands/*.md',
    '.claude/hooks',
    '.claude/rules',
    '.claude/rules/',
    '.claude/rules/*.md',
    '.claude/rules/api.md',
    '.claude/rules/api/',
    '.claude/rules/infra.md',
    '.claude/rules/ui/',
    '.claude/scripts/',
    '.claude/settings*.json',
    '.claude/settings.json',
    '.claude/settings.local.json',
    '.claude/skills/',
    '.claude/skills/<name>/SKILL.md',
    '.claude/skills/<owner>/scripts/<script>',
    '.claude/skills/shop-catalog/scripts/validate_sku.py',
    '.cursor/',
    '.cursor/agents/<verifier>.md',
    '.cursor/rules',
    '.cursor/rules/',
    '.cursor/rules/**',
    '.cursorrules',
    '.gemini/commands/*.toml',
    '.gemini/commands/shop/release.toml',
    '.gemini/settings.json',
    '.git',
    '.github',
    '.github/agents',
    '.github/agents/*.agent.md',
    '.github/chatmodes',
    '.github/chatmodes/',
    '.github/chatmodes/*.chatmode.md',
    '.github/copilot-instructions.md',
    '.github/instructions/',
    '.github/instructions/**.instructions.md',
    '.github/instructions/*.instructions.md',
    '.github/instructions/shop-api.instructions.md',
    '.gitignore',
    '.instructions.md',
    '.mcp.json',
    '.md',
    '.mdc',
    '.mdx',
    '.toml',
    '/* */',
    '//',
    '//abs',
    '/<subdir>:<name>',
    '/anthropic-skills:<name>',
    '/claude-api',
    '/code-review',
    '/command',
    '/commands reload',
    '/compact',
    '/config',
    '/context',
    '/doctor',
    '/etc/claude-code/CLAUDE.md',
    '/hooks',
    '/init',
    '/loop',
    '/mcp',
    '/memory',
    '/name',
    '/output-style',
    '/permissions',
    '/plugin',
    '/plugin update',
    '/relative-to-the-settings-source',
    '/reload-plugins',
    '/review',
    '/shop-kit:shop-release',
    '/shop:release',
    '/skill-doctor',
    '/skills',
    '/status',
    '/usr/bin/curl …',
    '01-agents-md-unread',
    '01-claude-local',
    '01-claude-md-exists',
    '01-claude-md-import',
    '01-claude-md-lines',
    '01-claude-md-size',
    '02-skill-frontmatter',
    '02-skill-md-exists',
    '02-skill-unknown-field',
    '03-skill-name-matches-folder',
    '04-skill-description-antitrigger',
    '04-skill-description-brackets',
    '04-skill-description-length',
    '05-skill-md-size',
    '06-skill-duplicate-name',
    '12-no-code-comments',
    '13-no-global-scripts',
    '14-rule-code-comments',
    '14-rule-english-only',
    '14-rule-no-paths',
    '14-rule-size',
    '14-rule-unknown-field',
    '15-skill-index',
    '16-reference-size',
    '17-always-loaded-budget',
    '18-see-skill-target',
    '1h',
    '21-skill-md-compaction',
    '22-rule-glob-match',
    '23-agent-frontmatter-keys',
    '24-settings-default-mode',
    '24-settings-env',
    '24-settings-keys',
    '24-settings-local',
    '24-settings-output-style',
    '24-settings-parse',
    '24-settings-scope',
    '24-settings-skill-overrides',
    '24-settings-statusline',
    '24-settings-unknown-key',
    '24-settings-unknown-subkey',
    '25-orphan-reference',
    '26-evals-anti-trigger',
    '26-evals-count',
    '26-evals-coverage',
    '26-evals-id-type',
    '26-evals-schema',
    '27-*',
    '27-twin-division-*',
    '28-skill-anchors',
    '29-listing-budget-derived',
    '30-plugin-cost',
    '31-overlay-unused',
    '32-skill-name-reserved',
    '32-skill-name-shape',
    '33-description-overlap',
    '35-hooks-*',
    '35-hooks-command',
    '35-hooks-context',
    '35-hooks-event',
    '35-hooks-if',
    '35-hooks-matcher',
    '35-hooks-parse',
    '35-hooks-shape',
    '35-hooks-timeout',
    '36-foreign-skill',
    '40-skill-not-loaded',
    '42-permissions-conflict',
    '42-permissions-rule',
    '43-mcp-approval',
    '43-mcp-credential-var',
    '43-mcp-secret',
    '43-mcp-shape',
    '44-plugin-layout',
    '44-plugin-path',
    '44-plugin-version',
    '45-command-shadowed',
    '48-agents-dir-skills',
    '50-security-broad-allow',
    '54-agents-md-variant',
    '55-cursor-reads-claude-md',
    '55-cursor-rule-glob',
    '55-cursor-rule-ignored',
    '55-cursor-rule-manual',
    '55-cursorrules-legacy',
    '56-copilot-apply-to',
    '56-copilot-chatmode',
    '56-copilot-instructions-name',
    '56-copilot-reads-claude-md',
    '57-gemini-',
    '57-gemini-command-no-prompt',
    '57-gemini-filename-excludes-gemini-md',
    '57-gemini-import-missing',
    '57-gemini-key-uncategorized',
    '57-runtime-log',
    '57-runtime-never-loaded',
    '57-runtime-rule-unscoped',
    ':*',
    ':-default',
    '; ',
    '; no duplicate ',
    '<hook> hook error',
    '<name>/RULE.md',
    '<name>/SKILL.md',
    '<page>.md',
    '<plugin>--v<version>',
    '<plugin>/skills/',
    '<plugin>/skills/<name>/SKILL.md',
    '<plugin>:',
    '<server>',
    '<verifier>',
    '<your-project-root>/.gemini/commands/',
    '>=1.4',
    '@../file.md',
    '@./file.md',
    '@./sub/file.md',
    '@/absolute/path/to/file.md',
    '@AGENTS.md',
    '@README',
    '@path',
    '@~/.claude/<my-instructions>.md',
    '@~/…',
    'A-Za-z0-9_-',
    'AGENTS.local.md',
    'AGENTS.md',
    'AGENTS.override.md',
    'ANTHROPIC_API_KEY',
    'ANTHROPIC_AUTH_TOKEN',
    'ANTHROPIC_BASE_URL',
    'ARGUMENTS: <value>',
    'AWS_BEARER_TOKEN_BEDROCK',
    'Agent',
    'Agent from <plugin> plugin',
    'Agent(<type>)',
    'Agent(Explore)',
    'Agent(model:opus)',
    'Any file',
    'Artifact',
    'AskUserQuestion',
    'Bash',
    'Bash(*)',
    'Bash(aws *)',
    'Bash(aws s3 ls)',
    'Bash(command:rm *)',
    'Bash(command:…)',
    'Bash(curl *)',
    'Bash(git *)',
    'Bash(git diff *)',
    'Bash(git push *)',
    'Bash(git:* push)',
    'Bash(ls *)',
    'Bash(ls*)',
    'Bash(npm run *)',
    'Bash(npm run lint)',
    'Bash(npm test)',
    'Bash(npx *)',
    'Bash(pwsh scripts/*)',
    'Bash(python*)',
    'Bearer <token>',
    'CLAUDE.local.md',
    'CLAUDE.md',
    'CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD=1',
    'CLAUDE_CODE_DISABLE_AUTO_MEMORY=1',
    'CLAUDE_CODE_DISABLE_BACKGROUND_TASKS=1',
    'CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS',
    'CLAUDE_CODE_ENABLE_TELEMETRY=1',
    'CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1',
    'CLAUDE_CODE_MAX_MCP_DESCRIPTION_LENGTH',
    'CLAUDE_CODE_MAX_SUBAGENT_SPAWN_DEPTH',
    'CLAUDE_CODE_SUBAGENT_MODEL',
    'CLAUDE_CODE_SUBAGENT_MODEL_FORCE',
    'CLAUDE_CONFIG_DIR',
    'CLAUDE_PLUGIN_OPTION_<KEY>',
    'CLAUDE_PLUGIN_ROOT',
    'CLAUDE_PROJECT_DIR',
    'CRITICAL',
    'Claude Browser',
    'Claude Preview',
    'Concise',
    'Contents:',
    'CwdChanged',
    'Default',
    'Division of responsibilities',
    'Do not use for: … (→ <other-skill>)',
    "Don't use for:",
    'ENABLE_TOOL_SEARCH=auto[:N]',
    'ENABLE_TOOL_SEARCH=false',
    'Edit',
    'Edit(src/**)',
    'Edit.*',
    'EndConversation',
    'EnterPlanMode',
    'EnterWorktree',
    'ExitPlanMode',
    'ExitWorktree',
    'Explanatory',
    'Explore',
    'FileChanged',
    'GEMINI.md',
    'Glob',
    'Global config',
    'Grep',
    'HOME',
    'HTTPS_PROXY',
    'Hook JSON output had unrecognized keys',
    'IMPORTANT',
    'InstructionsLoaded',
    'KNOWN_HOOK_EVENTS',
    'LSP',
    'Learning',
    'MAX_MCP_OUTPUT_TOKENS',
    'MCP server "<name>" has a "url" but no "type"',
    'MEMORY.md',
    'MUST use',
    'Managed',
    'MessageDisplay',
    'Monitor',
    'MultiEdit',
    'NPM_TOKEN',
    'NotebookEdit',
    'PermissionDenied',
    'PermissionRequest',
    'Plan',
    'PostModelSwitch',
    'PostToolBatch',
    'PostToolUse',
    'PostToolUseFailure',
    'PowerShell',
    'PowerShell(*)',
    'PreModelSwitch',
    'PreToolUse',
    'Proactive',
    'RUNTIME_MIN_SESSIONS',
    'Read',
    'Read(!sample.env)',
    'Read(*.env)',
    'Read(./.env)',
    'RegExp.test',
    'SKILL.md',
    'SLASH_COMMAND_TOOL_CHAR_BUDGET',
    'ScheduleWakeup',
    'SendMessage',
    'SessionEnd',
    'SessionStart',
    'Setup',
    'Skill',
    'Stop',
    'StopFailure',
    'SubagentHandback',
    'SubagentStart',
    'SubagentStop',
    'TMPDIR',
    'Task',
    'Task(...)',
    'TaskCompleted',
    'TaskCreated',
    'TaskOutput',
    'TaskStop',
    'TeammateIdle',
    'TodoWrite',
    'Tool',
    'Tool(param:value)',
    'Tool(specifier)',
    'ToolSearch',
    'Unexpected key(s) in SKILL.md frontmatter: …',
    'User or managed',
    'User, local, or managed',
    'UserPromptExpansion',
    'UserPromptSubmit',
    'WaitForMcpServers',
    'WebFetch',
    'WebFetch(domain:*)',
    'WebFetch(domain:docs.shop.example)',
    'WebFetch(domain:shop.example)',
    'WebSearch',
    'Workflow',
    'WorktreeCreate',
    'WorktreeRemove',
    'Write',
    'XDG_*',
    '[".git"]',
    '["src/api"]',
    '[08-agent-frontmatter]',
    '[08-agents-dir]',
    '[08b-agent-description]',
    '[09-agent-in-claude-md]',
    '[09-claude-md-agent-missing]',
    '[1m]',
    '[23-agent-frontmatter-keys]',
    '[23-agent-model]',
    '[23-agent-permission-mode]',
    '[23-agent-skills-preload]',
    '[23-agent-tools]',
    '[AUTO 01-agents-md-unread]',
    '[AUTO 01-claude-local]',
    '[AUTO 01-claude-md-exists]',
    '[AUTO 01-claude-md-import]',
    '[AUTO 01-claude-md-lines]',
    '[AUTO 01-claude-md-size]',
    '[AUTO 02-skill-frontmatter]',
    '[AUTO 02-skill-md-exists]',
    '[AUTO 02-skill-unknown-field]',
    '[AUTO 03-skill-name-matches-folder]',
    '[AUTO 04-skill-description-antitrigger]',
    '[AUTO 04-skill-description-brackets]',
    '[AUTO 04-skill-description-length]',
    '[AUTO 05-skill-md-size]',
    '[AUTO 06-skill-duplicate-name]',
    '[AUTO 07-skill-broken-link]',
    '[AUTO 08-agent-frontmatter]',
    '[AUTO 08b-agent-description]',
    '[AUTO 09-*]',
    '[AUTO 11-english-only]',
    '[AUTO 12-no-code-comments]',
    '[AUTO 13-no-global-scripts]',
    '[AUTO 14-rule-code-comments]',
    '[AUTO 14-rule-english-only]',
    '[AUTO 14-rule-no-paths]',
    '[AUTO 14-rule-size]',
    '[AUTO 14-rule-unknown-field]',
    '[AUTO 15-skill-index]',
    '[AUTO 16-reference-size]',
    '[AUTO 17-always-loaded-budget]',
    '[AUTO 18-see-skill-target]',
    '[AUTO 19-frontmatter-quoting]',
    '[AUTO 20-relative-links]',
    '[AUTO 21-skill-md-compaction]',
    '[AUTO 22-rule-glob-match]',
    '[AUTO 23-agent-frontmatter-keys]',
    '[AUTO 23-agent-model]',
    '[AUTO 23-agent-permission-mode]',
    '[AUTO 23-agent-skills-preload]',
    '[AUTO 23-agent-tools]',
    '[AUTO 24-settings-default-mode]',
    '[AUTO 24-settings-env]',
    '[AUTO 24-settings-local]',
    '[AUTO 24-settings-output-style]',
    '[AUTO 24-settings-parse]',
    '[AUTO 24-settings-scope]',
    '[AUTO 24-settings-skill-overrides]',
    '[AUTO 24-settings-statusline]',
    '[AUTO 24-settings-unknown-subkey]',
    '[AUTO 25-orphan-reference]',
    '[AUTO 26-evals-*]',
    '[AUTO 27-twin-division-*]',
    '[AUTO 28-config-anchors]',
    '[AUTO 28-skill-anchors]',
    '[AUTO 29-listing-budget-derived]',
    '[AUTO 30-plugin-cost]',
    '[AUTO 31-overlay-*]',
    '[AUTO 32-skill-name-reserved]',
    '[AUTO 32-skill-name-shape]',
    '[AUTO 33-description-overlap]',
    '[AUTO 34-*]',
    '[AUTO 35-hooks-command]',
    '[AUTO 35-hooks-context]',
    '[AUTO 35-hooks-event]',
    '[AUTO 35-hooks-if]',
    '[AUTO 35-hooks-matcher]',
    '[AUTO 35-hooks-parse]',
    '[AUTO 35-hooks-shape]',
    '[AUTO 35-hooks-timeout]',
    '[AUTO 36-foreign-skill]',
    '[AUTO 39-eval-*]',
    '[AUTO 40-skill-not-loaded]',
    '[AUTO 42-permissions-conflict]',
    '[AUTO 42-permissions-rule]',
    '[AUTO 43-mcp-approval]',
    '[AUTO 43-mcp-credential-var]',
    '[AUTO 43-mcp-secret]',
    '[AUTO 43-mcp-shape]',
    '[AUTO 44-plugin-layout]',
    '[AUTO 44-plugin-path]',
    '[AUTO 44-plugin-version]',
    '[AUTO 45-command-shadowed]',
    '[AUTO 46-doctrine-copy]',
    '[AUTO 48-agents-dir-skills]',
    '[AUTO 49-plugin-var-in-project]',
    '[AUTO 50-security-*]',
    '[AUTO 51-stale-command]',
    '[AUTO 52-claude-md-tree]',
    '[AUTO 53-no-verification-command]',
    '[AUTO 54-agents-md-variant]',
    '[AUTO 55-cursor-*]',
    '[AUTO 55-cursor-reads-claude-md, 56-copilot-reads-claude-md]',
    '[AUTO 56-copilot-*]',
    '[AUTO 57-runtime-*]',
    '[AUTO]',
    '[MANUAL]',
    '[]',
    '[order-id]',
    '\\[',
    '^2.0',
    '^2.0.0-0',
    '^…$',
    '_meta["anthropic/alwaysLoad"]',
    'acceptEdits',
    'additionalContext',
    'additionalDirectories',
    'agent',
    'agent-skills',
    'agent: <type>',
    'agent_id',
    'agent_type',
    'agents',
    'agents-md',
    'agents/',
    'agents/research/',
    'agents/review/',
    'agents/review/security.md',
    'allow',
    'allowCrossMarketplaceDependenciesOn',
    'allowManagedHooksOnly',
    'allowManagedMcpServersOnly: true',
    'allowed-tools',
    'allowedHttpHookUrls',
    'allowedMcpServers',
    'allowedMcpServers: []',
    'alwaysApply',
    'alwaysApply:',
    'alwaysLoad',
    'alwaysLoad: true',
    'anthropic',
    'anthropic-plugins',
    'anthropics/claude-code#93248',
    'api-*',
    'api-<vendor>',
    'api-error-shape.md',
    'api-express',
    'api-guidelines.md',
    'api-handler-shape.md',
    'api-socket',
    'api-socket/',
    'api/',
    'api/AGENTS.md',
    'api/GEMINI.md',
    'api/shop-api.mdc',
    'apiKeyHelper',
    'applyTo',
    'applyTo: "api/**"',
    'args',
    'argument-hint',
    'arguments',
    'array',
    'ask',
    'async',
    'async: true',
    'asyncRewake',
    'attribution',
    'audit.py',
    'audit.py --runtime',
    'auto',
    'autoAllowBashIfSandboxed',
    'autoConnectIde',
    'autoMemoryDirectory',
    'autoMemoryEnabled',
    'autoMode',
    'availableModels',
    'aws s3 ls',
    'background',
    'background: false',
    'background: true',
    'bar',
    'basePath',
    'bash',
    'bypassPermissions',
    'cacheTtl: 5m',
    'cargo',
    'cat',
    'chat.useAgentsMdFile',
    'chat.useClaudeMdFile',
    'chat.useNestedAgentsMdFiles',
    'claude',
    'claude --agent',
    'claude --debug',
    'claude --debug-file <path>',
    'claude --plugin-dir <repo>',
    'claude --safe-mode',
    'claude -p',
    'claude -p "<prompt>" --output-format stream-json --verbose',
    'claude doctor',
    'claude mcp add',
    'claude mcp add --transport ws',
    'claude mcp get <name>',
    'claude mcp list',
    'claude mcp list/get',
    'claude mcp reset-project-choices',
    'claude plugin eval',
    'claude plugin list',
    'claude plugin list --json',
    'claude plugin tag --push',
    'claude plugin validate',
    'claude plugin validate .claude/agents',
    'claude plugin validate .claude/skills',
    'claude plugin validate <dir>',
    'claude plugin validate [--strict]',
    'claude-*',
    'claude-api',
    'claude-in-chrome',
    'claude-md',
    'claude-md-and-agents-md',
    'claude-md-or-agents-md',
    'claude-plugins-official',
    'claudeMd',
    'claudeMdExcludes',
    'claude_code.*',
    'claude_code.skill_activated',
    'code-review',
    'code.claude.com',
    'code.claude.com/docs/en/',
    'code.claude.com/docs/en/<page>',
    'color',
    'command',
    'commands',
    'commands/',
    'commands/*.md',
    'commit',
    'compact',
    'compatibility',
    'computer-use',
    'content-strategy',
    'context.*',
    'context.discoveryMaxDirs',
    'context.fileName',
    'context.fileName: ["AGENTS.md"]',
    'context.includeDirectories',
    'context.loadMemoryFromIncludeDirectories',
    'context.memoryBoundaryMarkers',
    'context: fork',
    'continue',
    'copilot-instructions.md',
    'core.excludesFile',
    'core.symlinks',
    'curl -sL https://code.claude.com/docs/en/<page>.md',
    'cursor.com/docs/cli/using',
    'cursor.com/docs/rules',
    'cursor.com/docs/subagents',
    'cursor.com/help/customization/rules',
    'cursor.com/help/customization/skills',
    'data-*',
    'data-exports/**',
    'data-i18n',
    'data/[ab]*.csv',
    'date',
    'decision',
    'default',
    'defaultEnabled: false',
    'defaultMode',
    'deniedMcpServers',
    'deny',
    'dependencies',
    'dependency-unsatisfied',
    'dependency-version-unsatisfied',
    'description',
    'description:',
    'devbox run',
    'diffTool',
    'disable-model-invocation',
    'disable-model-invocation: true',
    'disableAllHooks',
    'disableBundledSkills: true',
    'disabledMcpServers',
    'disabledMcpjsonServers',
    'disallowed-tools',
    'disallowedTools',
    'disallowedTools: Bash(git push *)',
    'discoveryMaxDirs',
    'displayName',
    'dist/**',
    'docker exec',
    'docs.anthropic.com',
    'docs/',
    'docs/**/*.md, docs/**/*.mdx',
    'docs/notes.md',
    'domain:',
    'dontAsk',
    'echo',
    'effort',
    'enableAllProjectMcpServers',
    'enabledMcpServers',
    'enabledMcpjsonServers',
    'enabledPlugins',
    'env',
    'errors',
    'excludeAgent',
    'excludeAgent: \\"code-review\\"',
    'excludeAgent: \\"coding-agent\\"',
    'exit 1',
    'experimental',
    'experimental.monitors',
    'experimental.themes',
    'explanatory',
    'extraKnownMarketplaces',
    'fable',
    'fallbackModel',
    'false',
    'file_path',
    'foo',
    'force-for-plugin: true',
    'frontend/',
    'general-purpose',
    'gh',
    'git -C . push',
    'git log -1 --format=%ar -- .claude/skills/<name>',
    'git rm --cached CLAUDE.local.md',
    'github',
    'glob:',
    'globs',
    'globs:',
    'globs: ["*.ts", "*.js"]',
    'globs: api/**/*.ts, api/**/*.js',
    'google-gemini/gemini-cli',
    'grep -r',
    'haiku',
    'handoffs',
    'headers',
    'headersHelper',
    'headersHelper not run',
    'high',
    'hook error',
    'hookSpecificOutput',
    'hooks',
    'hooks § Common fields',
    'hooks § Exec form and shell form',
    'hooks § Exit code 0',
    'hooks § Exit code output',
    'hooks § HTTP response handling',
    'hooks § Hook handler fields',
    'hooks § Hook lifecycle',
    'hooks § Hook locations',
    'hooks § JSON output',
    'hooks § MCP tool hook fields',
    'hooks § Match MCP tools',
    'hooks § Matcher patterns',
    'hooks § Run hooks in the background',
    'hooks § Timeouts',
    'hooks § Workspace trust',
    'hooks-guide § Hook JSON has no effect',
    'hooks-guide § Hook not firing',
    'hooks-guide § Hooks and permission modes',
    'hooks-guide § Limitations',
    'hooks-guide § Stop hook hits the block cap',
    'hooks/',
    'hooks/hooks.json',
    'hooks:',
    'http',
    'if',
    'include',
    'includeGitInstructions',
    'infer',
    'inherit',
    'init',
    'initialPrompt',
    'initialUserMessage',
    'isError: true',
    'isolation',
    'kebab-case.md',
    'keep-coding-instructions: true',
    'keywords',
    'legacy-api-socket',
    'library',
    'license',
    'ln -s AGENTS.md CLAUDE.md',
    'loadFromIncludeDirectories',
    'load_reason',
    'local',
    'low',
    'lsof',
    'lspServers',
    'main',
    'managed-mcp.json',
    'managed-only',
    'managed-settings.json',
    'managedMcpServers',
    'manual',
    'marketplace.json',
    'max',
    'maxTurns',
    'mcp-anatomy.md',
    'mcp-servers',
    'mcpServers',
    'mcp__',
    'mcp__*',
    'mcp__.*__write.*',
    'mcp__<server>',
    'mcp__<server>__',
    'mcp__<server>__*',
    'mcp__<server>__.*',
    'mcp__<server>__<tool>',
    'mcp__plugin_<plugin>_<server>__<tool>',
    'mcp__plugin_shop-kit_search__<tool>',
    'mcp__search__.*',
    'mcp__shop-api',
    'mcp__shop-api__*',
    'mcp__shop-api__.*',
    'mcp__shop-api__get_*',
    'mcp__…(…)',
    'mcp_server.source',
    'mcp_server_errors',
    'mcp_tool',
    'medium',
    'memory',
    'memoryBoundaryMarkers',
    'memory_type',
    'metadata',
    'metadata.pluginRoot',
    'model',
    'model:',
    'model: opus',
    'modelPicker',
    'modelSettings',
    'name',
    'nested_traversal',
    'never expanded toward a remote server',
    'nice',
    'no-matching-tag',
    'nohup',
    'not configured',
    'npm',
    'npm run shop:seed',
    'npx',
    'official-claude-plugins',
    'omitClaudeMd',
    'omitClaudeMd: true',
    'onMounted',
    'once',
    'once: true',
    'options',
    'opus',
    'order-auditor',
    'org',
    'org-provisioned',
    'output-styles',
    'output-styles/',
    'outputStyle',
    'outputStyles',
    'owner.name',
    'package_skill.py',
    'parent_file_path',
    'path',
    'path escapes plugin directory',
    'path:',
    'path_glob_match',
    'paths',
    'paths:',
    'paths: ["src/api/**/*.ts"]',
    'paths: ["src/checkout/**"]',
    'permission-modes',
    'permissionDecision',
    'permissionMode',
    'permissionMode: plan',
    'permissions',
    'permissions § How permissions interact with sandboxing',
    'permissions § MCP',
    'permissions § Manage permissions',
    'permissions § Permission rule syntax',
    'permissions § Project allow rules and workspace trust',
    'permissions § Settings precedence',
    'permissions § Tool name wildcards',
    "permissions § What a Bash rule doesn't match",
    'permissions § What runs before you trust a folder',
    'permissions § What runs before…',
    'permissions § When your local settings file needs trust',
    'permissions.allow',
    'permissions.blockReadsOutsideWorkingDirectories',
    'permissions.defaultMode',
    'permissions.defaultMode: "bypassPermissions"',
    'pip',
    'plan',
    'platform.claude.com',
    'plugin',
    'plugin.json',
    'plugin:<plugin>:<server>',
    'plugin:name',
    'plugin:skill',
    'pluginConfigs',
    'pluginConfigs["agents-md@builtin"]',
    'plugins-reference',
    'plugins-reference § Plugin agent frontmatter',
    'plugins[]',
    'powershell',
    'pr',
    'profile: house',
    'project',
    'project_doc_max_bytes',
    'projects["<path>"].mcpServers',
    'prompt',
    'python',
    'python3',
    'quick_validate.py',
    'range-conflict',
    'react-patterns.mdc',
    'reason',
    'references/',
    'references/ssr-pitfalls.md',
    'refreshInterval',
    'release',
    'renames',
    'review',
    'run',
    'sandbox',
    'scripts/check_stock.py',
    'scripts/validate_sku.py',
    'search',
    'sed',
    'sensitive: true',
    'server',
    'serverCommand',
    'serverName',
    'serverUrl',
    'session_start',
    'settings',
    'settings § Exceptions to managed settings precedence',
    'settings § Fix a broken settings file',
    'settings § Keep personal settings out of a repository',
    'settings § Lists merge instead of overriding',
    'settings § Permission rules combine…',
    'settings § Settings precedence',
    'settings § Where Claude Code keeps the local file',
    'settings-reference § Settings index',
    'settings-reference § enableAllProjectMcpServers',
    'settings-reference § env',
    'settings-reference § permissions.defaultMode',
    'settings._json',
    'settings.json',
    'settings.local.json',
    'sh -c',
    "sh -c 'curl …'",
    'shell',
    'shop-*',
    'shop-api',
    'shop-api.mdc',
    'shop-catalog',
    'shop-checkout',
    'shop-db',
    'shop-import',
    'shop-kit',
    'shop-kit:order-auditor',
    'shop-kit:review:security',
    'shop-lore',
    'shop-preview',
    'shop-release',
    'shop-review',
    'shop-secrets',
    'shop-ssr',
    'shop-standard',
    'shop-tools',
    'skill-creator',
    'skill.name',
    'skillListingBudgetFraction',
    'skillListingMaxDescChars',
    'skillOverrides',
    'skills',
    'skills/',
    'skills/<name>/SKILL.md',
    'skills/shop-probe/SKILL.md',
    'skills:',
    'skipDangerousModePermissionPrompt',
    'sonnet',
    'source',
    'src',
    'src/api/**',
    'src/api/<name>.ts',
    'src/api/CLAUDE.md',
    'src/api/refunds.ts',
    'src/api/schema/',
    'src/billing/',
    'src/checkout/cart.js',
    'sse',
    'statusLine',
    'statusline § Manually configure',
    'statusline § Troubleshooting',
    'stdio',
    'stop_hook_active',
    'stream-json',
    'streamable-http',
    'strict',
    'strict: false',
    'string | string[]',
    'subagentStatusLine',
    'syncClaudeAiPlugins',
    'syncClaudeAiSkills',
    'synced',
    'system/init',
    'system:init',
    'systemMessage',
    'target',
    'timeout',
    'title',
    'tool',
    'tool:',
    'tool_used',
    'tools',
    'tools-reference',
    'translate',
    'trigger-words:',
    'trigger_file_path',
    'true',
    'true/false',
    'two-skills-compete',
    'type',
    'type: "sse"',
    'type: sse',
    'ui-*',
    'ui-components',
    'ui-components.mdc',
    'ui-composition',
    'ui-css',
    'ui-overview',
    'ui-scss',
    'ui-style.md',
    'ui/',
    'ui/shop-api.mdc',
    'undefined',
    'unknown',
    'url',
    'useAutoModeDuringPlan',
    'user',
    'user-invocable',
    'user-invocable: false',
    'userConfig',
    'uv',
    'validate',
    'validateImportPath',
    'version',
    'when_to_use',
    'window',
    'workflows',
    'workspace',
    'worktree',
    'ws',
    'xhigh',
    'yes/no/on/off/1/0',
    '{ code, message }',
    '{ …; }',
    '{"type":"system","subtype":"init"}',
    '{ui,api}/**/*.{ts,tsx}',
    '||',
    '|| true',
    '~/',
    '~/.cache/claude-audit/loads/<project folder>.jsonl',
    '~/.claude',
    '~/.claude.json',
    '~/.claude/',
    '~/.claude/.credentials.json',
    '~/.claude/.mcp.json',
    '~/.claude/CLAUDE.md',
    '~/.claude/agents/',
    '~/.claude/plugins/data/<id>/',
    '~/.claude/projects/<project>/memory/',
    '~/.claude/rules/',
    '~/.claude/settings.json',
    '~/.claude/skills/',
    '~/.claude/skills/<name>/SKILL.md',
    '~/.claude/skills/synced/',
    '~/.codex/AGENTS.override.md',
    '~/.gemini/<configured-name>',
    '~/.gemini/commands/',
    '~/.gemini/settings.json',
    '~/home',
    '~2.1.0',
    '§ Tool-specific permission rules',
    '→ <twin>',
    '→ ui-design agent',
    '⏸ Pending approval',
    '➜ See skill:',
    '➜ See skill: <name>',
})
